language: node_js
node_js: 6

cache:
  directories:
    - node_modules

matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      dist: trusty

script:
  - npm run dist

notifications:
  slack: ramme:44ubE4BVf3FGi8OldEKL743J
  email: false
